- name: Cópia de chaves do lado A
  hosts: lado-a
  become: true
  tasks:
    - name: Gera chaves lado a
      user:
        name: "{{ username }}"
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        force: no
       
    - name: Copia chaves lado A para o container
      fetch:
        src: "~/.ssh/id_rsa.pub"
        dest: "{{ inventory_hostname }}-id_rsa.pub"
        flat: yes
      become: yes
      become_user: "{{ username }}"

- name: Cópia de chaves do lado B
  hosts: lado-b
  become: true
  tasks:
    - name: Gera chaves labo b
      user:
        name: "{{ username }}"
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        force: no
       
    - name: Copia chaves lado B para o container
      fetch:
        src: "~/.ssh/id_rsa.pub"
        dest: "{{ inventory_hostname }}-id_rsa.pub"
        flat: yes
      become: yes
      become_user: "{{username}}"

- name: Copia chaves lado A para lado B
  hosts: lado-a
  become: true
  tasks:
    - name: Copia chaves para os servidores do lado b
      authorized_key:
        user: "{{username}}"
        state: present
        key: "{{ lookup('file', '{{item}}-id_rsa.pub') }}"
      with_items:
        - "{{ groups['lado-b'] }}"

- name: Copia chaves lado B para lado A
  hosts: lado-b
  become: true
  tasks:
    - name: Copia chaves para os servidores do lado b
      authorized_key:
        user: "{{username}}"
        state: present
        key: "{{ lookup('file', '{{item}}-id_rsa.pub') }}"
      with_items:
        - "{{ groups['lado-a'] }}"

- name: Remove arquivos temporarios
  hosts: localhost
  tasks:
    - name: Remove arquivos temporarios
      file:
        path: "{{ item }}-id_rsa.pub"
        state: absent
      with_items:
        - "{{ groups['all'] }}"